################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

################################################################################
# Book settings

title     : "immlib: An Immutable Scientific Workflow Library"
author    : Noah C. Benson  
copyright : "2025"
logo      : logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: immlib-docs.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/noahbenson/immlib
  path_to_book: docs
  branch: main

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
