################################################################################
# docs.yml
#
# GitHub Actions Workflow for building and publishing the immlib documentation.
# This is largely a modified version of the template given by the Jupyter book
# project, here: https://jupyterbook.org/en/stable/publish/gh-pages.html
#
# by Noah C. Benson

name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:
    
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip # Implicitly uses requirements.txt for cache key
      - name: Install immlib and Dependencies
        run: pip install -e .[docs]
      # Build the book
      - name: Build Documentation
        run: |
          jupyter-book build docs/immlib/
      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/immlib/_build/html"
      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
